language: cpp

# What branches are we reacting upon.
branches:
    only:
    - master

# Downloading ccache's cache is around 6s, uploading is around 3s.
cache: ccache

compiler:
- gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6

install:
- "[ $CC = gcc ] && export CC=gcc-6 || true"
- "[ $CXX = g++ ] && export CXX=g++-6 || true"


env:
  global:
    # For every new project, generate a new secret environment variable from the API access token from the automated build for the respective hub.docker.com project - travis encrypt DOCKER_HUB_OPENDLV_IO_PROXY_XXX_X86_64=YYYYYYY
    # DOCKER_HUB_OPENDLV_IO_PROXY_OXTS_X86_64
    - secure: "kw6T8Uyx/gwgWaCwmc26LfeAxiL9JGZ1b0fj4jFbEoWznexu4VEPIjFKyEQZBD2lPdAnKyzKvDCsyaTTjYc2gD74V96fwA4toTJEpC+57xqPB58d1NxySEOkBFAzdfwy0azP/w+J6Ycu1BQSLvKsSsAIURft7MmJSJ/1d3JQ7tPEvZhn0iUg3cxuZXZi4AQUnz5xAu6h7yzjD01nMrGYnvajr1fb/po7LR4TdoKau/56MIYjaVt7M3avgAxxTt6/VwDMpZn8ut7VFwabi4mofYL3K1EBPP9mWReV46U54RmWnepIlWb5ecuTaCygSus8llZ43fPi6diodfTMM+yW+8znQHN4OpgdLOeW3sxpSOCERXs/GmfniN9Lfu7dBZzyJZBOApHaAEfpAAFOzjlPD2/0xfltqNjSVioh4IpXFQA+0yEYpdsv58a5h/UDpeYyqPl/6naqnUn8UtJKFkpQCVIxp+orzphl33O/Vta2WDIYD1/oJ6T4a840amoQqkB2IDm5Jn+8G126m3Z5zHXZ13t1vEoUWZWJxAS1ziqITh7cK7vQ7Oswhbvh2ATMe+Ikh6fg0Y0jtgjXTxrY0lyjr/DrZTYhpCmkOQ2onfyAj6xPbShzOgdkJifaqIrGcRf7hy1cjy1389x1UYslFbhIdyneCF4lmTJv/6Hg9ZONVo4="
    # DOCKER_HUB_OPENDLV_IO_PROXY_OXTS_ARMHF
    - secure: "oipjjb6syFZkvkzz7TGmX+VmP401iZmlprLgJf/MrEij0jr63RkTz6FknItLZv9V/5h3PLoQVwOsSYyQNZHnkml+ChiqUrgYj7XK0+fCJTVOhIP50+Py4jJX3DELchEP8VH9F0Z0K58/5Tp73MGJjk2en9+mbE57JdXGjCUulPr3dIAT4kIk3I1PPs+ZmuT4Tb3iFTKcWIYCFzZRcMkJNKDPZ1/RQGvwPRaOt+5qdACzJAWpRUHC81/gN6TWAL60yZVX+NBD+1E+J5rWZ4176FktA8uVDbBRCk3L2Jlk7xPVclBdtCh3u7Xh6ExvlxrPO7IgklF4BUWkPtm9XJANYaBXxJSbcZHDgUFp5ScZFsbunTfhTevNKc+wKzbSg5EVUbmc1+4ZGQf0BNXznDsshr2groVnSIwIBjcPtFtco3zmBbRcsAtcf881ISKOXhcMjtwZOodSsv1vVECn40G1EwW0FJxUGvH+x3nNmGnYqt0YgmAcSvIIhx/45pjmhDs+4tYL6p4JX0+guZ7pIyQnTSZB1wgRKLPtmkLjmvzGdCarPlAOvLPz/qpqHp7uvsv+u7Xcwhel44BiriO+12gPSqdqXyv1wr2Fand3xGvpiqZgAi9CcM6ARPAKgUrcn/tKHkh1NJlL1+yGnU7xWnQus6RO7ETgU4golK7NjXn5plk="
    # DOCKER_HUB_OPENDLV_IO_PROXY_OXTS_AARCH64
    - secure: "ec8h5d8Cvu7kLtjdM3PruXOB2JigM/lDeiEi6fiw8Ac3o6fePq/N9bbobY9Gc5Wp7BfI9+4YrTfWt6tdCJV/bpQGWexByjId7DXW+9D76fI9L47GjSRyrOshiaALvoL5jKSeMLNIEODq8p1mtqZPPvHgsJOoKF6Mj5LA7PWwgCAAqzhsNO14SuKnY6KREMh3vSf267tA/p9MoLCqcbHUhek9KPnUOMAguNDPTydK6OUaHgeWENgLImWFekKpjLHgPcjTaF54P/jRcOv0KcVhOXc9Mkn5rh53qKw6SiRQ4+q1LEnHzaH8I/Wpq3K8p4iAfb70qDEm+E86lckx4VigDJXJdW2+VVyL9YtU+ElEF5z4cAxziDih/HYd7sgjzb5NwMWz2hE2cgR5lkvA5p5EOZTqtZtBLuGphQlJJzIDfZA5/oswbtCEOrmoisW7cyqFHz4UskmGn4/kXAqWcp4ztJ99k9SDNe7HnDiRBQ/PRkfBmX7EEnGov5u0oRIRCB2um7s5Kl6dQr8owDGRjOEaAMQZx1/d8nOHzm3W94UUFi0MhonSIhM84IGyRcESqsLRZJvahpjH/IBC8pD2/ikLI5AE87VYx4cJH7klQXdgyFAQF9Hh/cPLB+j+t50jDA/Btuk07K7BGLWif6A45JaTvn5+w+J3OIdEBb2012TbMTg="


before_script:
# Check what projects need to be built.
- PROXY_OXTS=$(git diff HEAD~ --name-only | grep "proxy-oxts/" >/dev/null && echo "proxy-oxts" || echo "")
- PROXY_TRIMBLE=$(git diff HEAD~ --name-only | grep "proxy-trimble/" >/dev/null && echo "proxy-trimble" || echo "")


script:
# Build the projects.
#- if [[ "${PROXY_OXTS}" != "" ]]; then cd ${PROXY_OXTS} && mkdir -p build && cd build && cmake .. && make && make test && curl --data build=true -X POST https://registry.hub.docker.com/u/chalmersrevere/opendlv.io-${PROXY_OXTS}/trigger/$DOCKER_HUB_OPENDLV_IO_PROXY_OXTS_X86_64/ && curl --data build=true -X POST https://registry.hub.docker.com/u/chalmersrevere/opendlv.io-${PROXY_OXTS}-armhf/trigger/$DOCKER_HUB_OPENDLV_IO_PROXY_OXTS_ARMHF/ && curl --data build=true -X POST https://registry.hub.docker.com/u/chalmersrevere/opendlv.io-${PROXY_OXTS}-aarch64/trigger/$DOCKER_HUB_OPENDLV_IO_PROXY_OXTS_AARCH64/; fi
#- if [[ "${PROXY_OXTS}" != "" ]]; then cd ${PROXY_OXTS} && mkdir -p build && cd build && cmake .. && make && make test && ../../.docker.sh https://registry.hub.docker.com/u/chalmersrevere/opendlv.io-${PROXY_OXTS}/trigger/$DOCKER_HUB_OPENDLV_IO_PROXY_OXTS_X86_64/ v`cat ../VERSION` && ../../.docker.sh https://registry.hub.docker.com/u/chalmersrevere/opendlv.io-${PROXY_OXTS}-armhf/trigger/$DOCKER_HUB_OPENDLV_IO_PROXY_OXTS_ARMHF/ v`cat ../VERSION` && ../../.docker.sh https://registry.hub.docker.com/u/chalmersrevere/opendlv.io-${PROXY_OXTS}-aarch64/trigger/$DOCKER_HUB_OPENDLV_IO_PROXY_OXTS_AARCH64/ v`cat ../VERSION`; fi
- if [[ "${PROXY_OXTS}" != "" ]]; then cd ${PROXY_OXTS} && mkdir -p build && cd build && cmake .. && make && make test && ../../.docker.sh https://registry.hub.docker.com/u/chalmersrevere/opendlv.io-${PROXY_OXTS}/trigger/$DOCKER_HUB_OPENDLV_IO_PROXY_OXTS_X86_64/ v`cat ../VERSION`; fi


notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: hT0aR7BpGKmXlR4JxHSVsn4q6ofbNWvo3UWpHLgoiXGdpCeQ9Aczu8nMcG4ybnGMrg/PeSnvsHjaIvtgKfow35MCWur0uygQNqZiiaDjDEEeLzcvYo8/v6PKqpp2VOPqIEzXjZxAR8sWB82W8f/xXuB5tVaFdVXToA2UOBdlS49tc51wunj8DPx17NE6B8uvU4Zo4g0dpg5x31uzXvjOkH48y8V58JgaXgATojzRoEEV2jytlZUumA4KM5zOGZnAkGO2iC0lxbRnZROArSAd0A4Tg4cxDXuWFIxM9m9c5YxHtwMYMb5wWeAHRT4zGYVZeYjs5wOjZfTOzsihXGt1kEumTv6AxME0BYxeZQuw+fOapAyARqvuOnkUADBwxfK0Mwqb4HI2uffirz20v6XA0WmOQTuXL6K5Sy/+O4O076rFCHYUcpntHqXKeHGw9ERGBOaaLjOdm+ga7zbeTXbqdAw/h0Y8iYc2UyB5ChS9ysOJnMmcoLfTLJmNes0ll4dt9QNDR+01oASor5S7XVfe148+sZqhCM+fn6vudWSlxbhuyddFvAm0bEM/aqNQm9uvKgwB85BO8C6DRiGXjdWRjqF0aPhZrtHrJb7xZeStdDxXuI+5YHK6wSChgw8WX7zMsTgZ2UYBUURsmnwkNPTMhh53CHmRKSu8LGApUq2oGhc=
