language: cpp

# What branches are we reacting upon.
branches:
    only:
    - /^pre-release-proxy-oxts$/
    - /^pre-release-proxy-trimble$/

# Downloading ccache's cache is around 6s, uploading is around 3s.
cache: ccache

compiler:
- gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6

install:
- "[ $CC = gcc ] && export CC=gcc-6 || true"
- "[ $CXX = g++ ] && export CXX=g++-6 || true"


script:
- cd `echo ${TRAVIS_BRANCH} | sed -e 's/pre-release-//'` && mkdir -p build && cd build && cmake .. && make && make test; fi


notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: hT0aR7BpGKmXlR4JxHSVsn4q6ofbNWvo3UWpHLgoiXGdpCeQ9Aczu8nMcG4ybnGMrg/PeSnvsHjaIvtgKfow35MCWur0uygQNqZiiaDjDEEeLzcvYo8/v6PKqpp2VOPqIEzXjZxAR8sWB82W8f/xXuB5tVaFdVXToA2UOBdlS49tc51wunj8DPx17NE6B8uvU4Zo4g0dpg5x31uzXvjOkH48y8V58JgaXgATojzRoEEV2jytlZUumA4KM5zOGZnAkGO2iC0lxbRnZROArSAd0A4Tg4cxDXuWFIxM9m9c5YxHtwMYMb5wWeAHRT4zGYVZeYjs5wOjZfTOzsihXGt1kEumTv6AxME0BYxeZQuw+fOapAyARqvuOnkUADBwxfK0Mwqb4HI2uffirz20v6XA0WmOQTuXL6K5Sy/+O4O076rFCHYUcpntHqXKeHGw9ERGBOaaLjOdm+ga7zbeTXbqdAw/h0Y8iYc2UyB5ChS9ysOJnMmcoLfTLJmNes0ll4dt9QNDR+01oASor5S7XVfe148+sZqhCM+fn6vudWSlxbhuyddFvAm0bEM/aqNQm9uvKgwB85BO8C6DRiGXjdWRjqF0aPhZrtHrJb7xZeStdDxXuI+5YHK6wSChgw8WX7zMsTgZ2UYBUURsmnwkNPTMhh53CHmRKSu8LGApUq2oGhc=

